In [1]:
import numpy as np
from sklearn.model_selection import KFold
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([1, 2, 3, 4])
kf = KFold(n_splits=3)

In [2]:
kf.get_n_splits(X)

3

In [3]:
print(kf)

KFold(n_splits=3, random_state=None, shuffle=False)


In [4]:
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    #X_train, X_test = X[train_index], X[test_index]
    #y_train, y_test = y[train_index], y[test_index]   
  

TRAIN: [2 3] TEST: [0 1]
TRAIN: [0 1 3] TEST: [2]
TRAIN: [0 1 2] TEST: [3]


In [5]:
X_train

NameError: name 'X_train' is not defined

In [6]:
X[train_index]

array([[1, 2],
       [3, 4],
       [1, 2]])

In [7]:
train_index

array([0, 1, 2])

In [8]:
test_index

array([3])

In [9]:
X_test

NameError: name 'X_test' is not defined

In [10]:
y_train

NameError: name 'y_train' is not defined

In [11]:
y_test

NameError: name 'y_test' is not defined

In [12]:
kf.split(X)

<generator object _BaseKFold.split at 0x7fef28047a50>