In [1]:
import pandas as pd
import numpy as np

In [2]:
IF = pd.read_csv('IF_Outliers.csv')

In [3]:
Dropped = pd.read_csv('BaseDropIF.csv')

In [4]:
IF.shape

(14, 182)

In [5]:
Dropped.shape

(2566, 299)

In [6]:
Dropped

Unnamed: 0  MSSubClass_150  MSSubClass_160  MSSubClass_180  \
0              0               0               0               0   
1              1               0               0               0   
2              2               0               0               0   
3              3               0               0               0   
4              4               0               0               0   
...          ...             ...             ...             ...   
2561        2575               0               0               0   
2562        2576               0               0               0   
2563        2577               0               0               0   
2564        2578               0               0               0   
2565        2579               0               0               0   

      MSSubClass_190  MSSubClass_20  MSSubClass_30  MSSubClass_40  \
0                  0              0              1              0   
1                  0              0              0              0   
2                  0              0              1              0   
3                  0              0              0              0   
4                  0              0              0              0   
...              ...            ...            ...            ...   
2561               0              0              1              0   
2562               0              1              0              0   
2563               0              0              0              0   
2564               0              0              0              0   
2565               0              0              0              0   

      MSSubClass_45  MSSubClass_50  ...  GarageYrBlt  GarageCars  GarageArea  \
0                 0              0  ...       1939.0         2.0       399.0   
1                 0              0  ...       1984.0         1.0       266.0   
2                 0              0  ...       1930.0         1.0       216.0   
3                 0              0  ...       1940.0         1.0       281.0   
4                 0              0  ...       2001.0         2.0       528.0   
...             ...            ...  ...          ...         ...         ...   
2561              0              0  ...       1916.0         1.0       192.0   
2562              0              0  ...       1955.0         2.0       452.0   
2563              0              0  ...       1949.0         3.0       871.0   
2564              0              0  ...       2000.0         2.0       486.0   
2565              0              0  ...       1993.0         2.0       471.0   

      WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  \
0              0            0              0          0          166   
1              0          105              0          0            0   
2            154            0             42         86            0   
3              0            0            168          0          111   
4              0           45              0          0            0   
...          ...          ...            ...        ...          ...   
2561           0           98              0          0           40   
2562           0            0              0          0            0   
2563           0            0              0          0            0   
2564         193           96              0          0            0   
2565         182           81              0          0            0   

      PoolArea  MiscVal  
0            0        0  
1            0        0  
2            0        0  
3            0        0  
4            0        0  
...        ...      ...  
2561         0        0  
2562         0        0  
2563         0        0  
2564         0        0  
2565         0        0  

[2566 rows x 299 columns]

In [7]:
Dropped.index.values

array([   0,    1,    2, ..., 2563, 2564, 2565])

In [8]:
Dropped[['Unnamed: 0']].values

array([[   0],
       [   1],
       [   2],
       ...,
       [2577],
       [2578],
       [2579]])

In [9]:
diff = np.setdiff1d(Dropped.index.values, Dropped[['Unnamed: 0']].values, assume_unique=False)

In [10]:
diff

array([  50,  309,  487,  533, 1007, 1233, 1634, 1910, 2004, 2204, 2273,
       2323, 2425, 2436])

In [11]:
check = pd.read_csv('IF_Outliers.csv')

In [12]:
check

Unnamed: 0  MSSubClass  MSZoning  Street  Alley  LotShape  LandContour  \
0           50        15.0       5.0     1.0    1.0       3.0          3.0   
1          309        10.0       5.0     1.0    1.0       0.0          0.0   
2          487        13.0       5.0     1.0    1.0       0.0          2.0   
3          533        10.0       5.0     1.0    1.0       1.0          2.0   
4         1007        10.0       5.0     1.0    1.0       0.0          3.0   
5         1233         6.0       5.0     1.0    1.0       0.0          2.0   
6         1634         4.0       5.0     0.0    1.0       0.0          1.0   
7         1910         4.0       6.0     1.0    1.0       2.0          0.0   
8         2004        12.0       6.0     1.0    1.0       1.0          3.0   
9         2204        15.0       4.0     1.0    2.0       3.0          3.0   
10        2273         6.0       6.0     1.0    1.0       3.0          3.0   
11        2323         6.0       3.0     0.0    1.0       3.0          3.0   
12        2425         4.0       6.0     1.0    1.0       3.0          3.0   
13        2436         9.0       6.0     1.0    0.0       3.0          3.0   

    Utilities  LotConfig  LandSlope  ...  91  92  93  94  95  96  97  98  99  \
0         0.0        4.0        0.0  ...  -1  -1  -1  -1  -1  -1  -1  -1  -1   
1         0.0        4.0        0.0  ...  -1  -1  -1  -1  -1  -1  -1  -1  -1   
2         0.0        0.0        0.0  ...  -1  -1  -1  -1  -1  -1  -1  -1  -1   
3         0.0        1.0        2.0  ...  -1  -1  -1  -1  -1  -1  -1  -1  -1   
4         0.0        0.0        0.0  ...  -1  -1  -1  -1  -1  -1  -1  -1  -1   
5         0.0        4.0        2.0  ...  -1  -1  -1  -1  -1  -1  -1  -1  -1   
6         0.0        0.0        2.0  ...  -1  -1  -1  -1  -1  -1  -1  -1  -1   
7         0.0        0.0        0.0  ...  -1  -1  -1  -1  -1  -1  -1  -1  -1   
8         0.0        4.0        0.0  ...  -1  -1  -1  -1  -1  -1  -1  -1  -1   
9         0.0        4.0        0.0  ...  -1  -1  -1  -1  -1  -1  -1  -1  -1   
10        0.0        4.0        0.0  ...  -1  -1  -1  -1  -1  -1  -1  -1  -1   
11        1.0        4.0        0.0  ...  -1  -1  -1  -1  -1  -1  -1  -1  -1   
12        0.0        4.0        0.0  ...  -1  -1  -1  -1  -1  -1  -1  -1  -1   
13        0.0        0.0        0.0  ...  -1  -1  -1  -1  -1  -1  -1  -1  -1   

    Sum  
0  -100  
1  -100  
2  -100  
3  -100  
4  -100  
5  -100  
6  -100  
7  -100  
8  -100  
9  -100  
10 -100  
11 -100  
12 -100  
13 -100  

[14 rows x 182 columns]

In [13]:
diff2 = np.setdiff1d(diff, check[['Unnamed: 0']].values, assume_unique=False)

In [14]:
diff2

array([], dtype=int64)