In [1]:
import pandas as pd
import numpy as np

In [2]:
IF = pd.read_csv('IF_Outliers.csv')

In [3]:
Dropped = pd.read_csv('OrdinalDropIF.csv')

In [4]:
IF.shape

(12, 185)

In [5]:
Dropped.shape

(2568, 83)

In [6]:
Dropped

Unnamed: 0  MSSubClass  MSZoning  Street  Alley  LotShape  LandContour  \
0              0         6.0       5.0     1.0    1.0       3.0          3.0   
1              1         0.0       5.0     1.0    1.0       3.0          3.0   
2              2         6.0       1.0     1.0    1.0       3.0          3.0   
3              3        11.0       5.0     1.0    1.0       3.0          3.0   
4              4        10.0       5.0     1.0    1.0       3.0          3.0   
...          ...         ...       ...     ...    ...       ...          ...   
2563        2575         6.0       5.0     1.0    1.0       3.0          3.0   
2564        2576         5.0       5.0     1.0    1.0       0.0          3.0   
2565        2577        15.0       4.0     1.0    1.0       3.0          1.0   
2566        2578        10.0       5.0     1.0    1.0       3.0          3.0   
2567        2579        10.0       5.0     1.0    1.0       0.0          3.0   

      Utilities  LotConfig  LandSlope  ...  GarageYrBlt  GarageCars  \
0           0.0        0.0        0.0  ...       1939.0         2.0   
1           0.0        4.0        0.0  ...       1984.0         1.0   
2           0.0        4.0        0.0  ...       1930.0         1.0   
3           0.0        0.0        0.0  ...       1940.0         1.0   
4           0.0        4.0        0.0  ...       2001.0         2.0   
...         ...        ...        ...  ...          ...         ...   
2563        0.0        4.0        0.0  ...       1916.0         1.0   
2564        0.0        1.0        0.0  ...       1955.0         2.0   
2565        0.0        4.0        0.0  ...       1949.0         3.0   
2566        0.0        4.0        0.0  ...       2000.0         2.0   
2567        0.0        4.0        0.0  ...       1993.0         2.0   

      GarageArea  WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  \
0          399.0           0            0              0          0   
1          266.0           0          105              0          0   
2          216.0         154            0             42         86   
3          281.0           0            0            168          0   
4          528.0           0           45              0          0   
...          ...         ...          ...            ...        ...   
2563       192.0           0           98              0          0   
2564       452.0           0            0              0          0   
2565       871.0           0            0              0          0   
2566       486.0         193           96              0          0   
2567       471.0         182           81              0          0   

      ScreenPorch  PoolArea  MiscVal  
0             166         0        0  
1               0         0        0  
2               0         0        0  
3             111         0        0  
4               0         0        0  
...           ...       ...      ...  
2563           40         0        0  
2564            0         0        0  
2565            0         0        0  
2566            0         0        0  
2567            0         0        0  

[2568 rows x 83 columns]

In [7]:
Dropped.index.values

array([   0,    1,    2, ..., 2565, 2566, 2567])

In [8]:
Dropped[['Unnamed: 0']].values

array([[   0],
       [   1],
       [   2],
       ...,
       [2577],
       [2578],
       [2579]])

In [9]:
diff = np.setdiff1d(Dropped.index.values, Dropped[['Unnamed: 0']].values, assume_unique=False)

In [10]:
diff

array([  50,  309,  487,  802, 1007, 1233, 2004, 2204, 2273, 2323, 2425,
       2436])

In [11]:
check = pd.read_csv('IF_Outliers.csv')

In [12]:
check

Unnamed: 0  Unnamed: 0.1  MSSubClass  MSZoning  Street  Alley  LotShape  \
0           50            50        15.0       5.0     1.0    1.0       3.0   
1          309           309        10.0       5.0     1.0    1.0       0.0   
2          487           487        13.0       5.0     1.0    1.0       0.0   
3          802           802        10.0       5.0     1.0    1.0       1.0   
4         1007          1007        10.0       5.0     1.0    1.0       0.0   
5         1233          1233         6.0       5.0     1.0    1.0       0.0   
6         2004          2004        12.0       6.0     1.0    1.0       1.0   
7         2204          2204        15.0       4.0     1.0    2.0       3.0   
8         2273          2273         6.0       6.0     1.0    1.0       3.0   
9         2323          2323         6.0       3.0     0.0    1.0       3.0   
10        2425          2425         4.0       6.0     1.0    1.0       3.0   
11        2436          2436         9.0       6.0     1.0    0.0       3.0   

    LandContour  Utilities  LotConfig  ...  91  92  93  94  95  96  97  98  \
0           3.0        0.0        4.0  ...  -1  -1  -1  -1  -1  -1  -1  -1   
1           0.0        0.0        4.0  ...  -1  -1  -1  -1  -1  -1  -1  -1   
2           2.0        0.0        0.0  ...  -1  -1  -1  -1  -1  -1  -1  -1   
3           1.0        0.0        1.0  ...  -1  -1  -1  -1  -1  -1  -1  -1   
4           3.0        0.0        0.0  ...  -1  -1  -1  -1  -1  -1  -1  -1   
5           2.0        0.0        4.0  ...  -1  -1  -1  -1  -1  -1  -1  -1   
6           3.0        0.0        4.0  ...  -1  -1  -1  -1  -1  -1  -1  -1   
7           3.0        0.0        4.0  ...  -1  -1  -1  -1  -1  -1  -1  -1   
8           3.0        0.0        4.0  ...  -1  -1  -1  -1  -1  -1  -1  -1   
9           3.0        1.0        4.0  ...  -1  -1  -1  -1  -1  -1  -1  -1   
10          3.0        0.0        4.0  ...  -1  -1  -1  -1  -1  -1  -1  -1   
11          3.0        0.0        0.0  ...  -1  -1  -1  -1  -1  -1  -1  -1   

    99  Sum  
0   -1 -100  
1   -1 -100  
2   -1 -100  
3   -1 -100  
4   -1 -100  
5   -1 -100  
6   -1 -100  
7   -1 -100  
8   -1 -100  
9   -1 -100  
10  -1 -100  
11  -1 -100  

[12 rows x 185 columns]

In [13]:
diff2 = np.setdiff1d(diff, check[['Unnamed: 0']].values, assume_unique=False)

In [14]:
diff2

array([], dtype=int64)